version: '3'

services:
  backend:
    build: ./backend
  #  container_name: backend_sync_aws
    ports:
      - 5000:5000
    # environment:
    #   PORT: 5000
    #   FLASK_DEBUG: 1
    # expose: 
    #   - 5000
    networks:
      - mynetwork

  frontend:
    build: ./frontend
   # container_name: frontend_sync_aws
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge


# version: '3'

# services:
#   backend:
#     build: ./backend
#     container_name: backend_sync_aws
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./backend:/app
#     environment:
#       - AWS_ACCESS_KEY_ID=""
#       - AWS_SECRET_ACCESS_KEY=""
#       - AWS_REGION=us-east-1
#       - S3_BUCKET=myawsbucket-s3-ada

#   frontend:
#     build: ./frontend
#     container_name: frontend_sync_aws
#     ports:
#       - "80:80"
#     volumes:
#       - ./frontend:/usr/share/nginx/html




# version: '3'

# services:
#   backend:
#     build: ./backend
#     container_name: backend_sync_aws
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./backend:/app
#     environment:
#       - AWS_ACCESS_KEY_ID=""
#       - AWS_SECRET_ACCESS_KEY=""
#       - AWS_REGION=us-east-1
#       - S3_BUCKET=myawsbucket-s3-ada
#     depends_on:
#       - s3

#   s3:
#     image: minio/minio
#     container_name: s3_sync_aws
#     ports:
#       - "9000:9000"
#     environment:
#       MINIO_ROOT_USER: minioadmin #
#       MINIO_ROOT_PASSWORD: minioadmin #
#     volumes:
#       - ./data:/data
#       - ./config:/root/.minio
#     command: server /data

#   frontend:
#     build: ./frontend
#     container_name: frontend_sync_aws
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend:/app
#     depends_on:
#       - backend
