version: '3'

services:
  backend:
    build: ./backend
    container_name: backend_sync_aws
    ports:
      - 5000:5000
    # environment:
    #   PORT: 5000
    #   FLASK_DEBUG: 1
    # expose: 
    #   - 5000
    networks:
      - mynetwork
    volumes:
      - ./.aws:/root/.aws

  frontend:
    build: ./frontend
    container_name: frontend_sync_aws
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge


#https://www.sambaiz.net/en/article/426/