version: '3.8'

services:
  backend:
    build: ./back_end
    ports:
      - "5000:5000"
    volumes:
      - ./back_end:/app
      - ./data:/app/data

  frontend:
    build: ./front_end
    ports:
      - "8080:8080"
    volumes:
      - ./front_end:/app
