name: Deploy to AWS S3 #Deploy Terraform
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v3
      #   with:
      #     terraform_version: 1.8.2 # 0.14.4 
      
      # - name: terraform plan
      #   uses: dflook/terraform-plan@v1
      #   with:
      #     path: terraform

      - name: Initialize Terraform
        run:  |
          cd terraform
          terraform init

      - name: Plan Terraform
        run:  |
          cd terraform
          terraform plan

      - name: Apply Terraform
        run:  |
          cd terraform
          terraform apply -auto-approve
        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
      
      # - name: Listar buckets
      #   run: aws s3 ls

      # - name: Deploy static site to S3 bucket
      #   run: aws s3 sync . s3://<bucket-name> --delete


# .github/workflows/terraform.yml

      
