name: Deploy to AWS S3 #Deploy Terraform
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types: [opened, synchronize, reopened]

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

# permissions:
#   issues: write
#   actions: write
#   checks: write
#   contents: write
#   deployments: write
#   id-token: write
#   discussions: write
#   pull-requests: write
#   repository-projects: write
#   statuses: write


jobs:
  list_buckets:
    runs-on: ubuntu-latest

    steps:
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
      - name: Listar buckets
        run: aws s3 ls
    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   AWS_DEFAULT_REGION: "us-east-1"

  terraform:
    runs-on: ubuntu-latest
    #needs: create_s3_bucket  # Ensure the S3 bucket job runs first
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1" 

      - name: Enable S3 bucket versioning
        run: |
          aws s3api put-bucket-versioning --bucket myawsbucket-s3-ada --versioning-configuration Status=Enabled
          aws s3api put-bucket-encryption --bucket myawsbucket-s3-ada --server-side-encryption-configuration '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform/
          terraform init

      - name: Terraform Validate
        run: |
          cd terraform/
          terraform validate

      - name: Terraform Plan
        run: |
          cd terraform/
          terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
      
      - name: Terraform Apply
        run: |
          cd terraform/
          terraform apply -auto-approve

# .github/workflows/terraform.yml

      
